### ISSUE TITLE
share

### ISSUE THREAD

**Issue by rajveer01** [rajveer01/homeAutomation#1]
```
cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://tapo_admin:tapo_admin@192.168.1.230:554/stream1
          roles:
            - record  # Only recording, no detection or rtmp
    # No 'detect' section

# Optional: Database configuration
database:
  path: /media/frigate/frigate.db

# Snapshots disabled
snapshots:
  enabled: False

mqtt:
  enabled: False

ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -an
    # -an disables audio recording; remove if you want audio

record:
  enabled: True

birdseye:
  enabled: False
```

**Comment by rajveer01** [comment]
Chat gpt

```
cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://tapo_admin:tapo_admin@192.168.1.230:554/stream1
          roles:
            - record
    detect:
      enabled: False  # disable detection entirely

ffmpeg:
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy

record:
  enabled: True
  retain:
    days: 7  # adjust how many days to retain recordings
  events:
    enabled: False  # we don't need event recording without detection

snapshots:
  enabled: False  # disable snapshots

birdseye:
  enabled: False  # disable birdseye view

mqtt:
  enabled: False

database:
  path: /media/frigate/frigate.db
```

**Comment by rajveer01** [comment]
r1

```
mqtt:
  enabled: false

cameras:
  tapo_cam:
    ffmpeg:
      inputs:
        - path: rtsp://tapo_admin:tapo_admin@192.168.1.230:554/stream1
          input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
          roles:
            - record
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    detect:
      enabled: false
    snapshots:
      enabled: false
    live:
      height: 0  # 0 means original resolution

```

**Comment by rajveer01** [comment]
2025-05-03 18:47:25.417181619  [ERROR] Trying to migrate the db path from '/media/frigate/frigate.db' to the '/config' dir, but '/config' is not a mountpoint, please mount the '/config' dir

**Comment by rajveer01** [comment]
r1 2
```
database:
  path: /media/frigate/frigate.db  # or another path that exists on your system

cameras:
  tapo_cam:
    ffmpeg:
      inputs:
        - path: rtsp://tapo_admin:tapo_admin@192.168.1.230:554/stream1
          input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
          roles:
            - record
    record:
      enabled: true
      retain:
        days: 7
        mode: all
    detect:
      enabled: false
    snapshots:
      enabled: false
    live:
      height: 0
```
